# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('time', models.TimeField()),
                ('departure_port', models.CharField(max_length=5)),
                ('arrival_port', models.CharField(max_length=5)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ticket_type', models.CharField(default='Normal', max_length=25)),
                ('sit_class', models.CharField(default='Trevaler', max_length=3)),
                ('carrier', models.CharField(default='Aiur', max_length=5)),
            ],
        ),
    ]
