# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='sit_class',
            field=models.CharField(default='Trevaler', max_length=20),
        ),
    ]
