# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 04:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20160501_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 1, 4, 44, 52, 919000, tzinfo=utc)),
        ),
    ]
