# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 04:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_ticket_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 1, 4, 48, 10, 483000, tzinfo=utc)),
        ),
    ]
