# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20160501_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
